# Generated by Django 4.2.9 on 2024-01-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='article',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='twitter_title',
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description that will appear on social media posts. It is limited to 300 characters, but it is recommended that you do not use anything over 200.', max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title that will appear on social media posts. This is limited to 100 characters, but Facebook will truncate the title to 88 characters.', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='A unique portion of the URL that is used to identify this specific page using human-readable keywords (e.g., about-us)', max_length=150),
        ),
    ]
