# Generated by Django 4.2.9 on 2024-01-28 11:07

from django.db import migrations, models
import django.db.models.deletion
import uncms.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0012_remove_page_twitter_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "page",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="pages.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", uncms.models.fields.HtmlField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.page"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
