# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
